# Generated by Django 5.2 on 2025-05-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lesson_options_lesson_order_quiz_passing_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='prerequisites',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
