# Generated by Django 5.2 on 2025-05-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lesson_prerequisites_lesson_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visibility_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
